repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-toml
      - id: check-json
        exclude: ".*\\.vscode/"
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: debug-statements
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma
        name: add training comma

  # TODO: Wait for release https://github.com/PyCQA/docformatter/issues/293
  # Problem: https://github.com/PyCQA/docformatter/pull/287#issue-2568300589
  - repo: https://github.com/pycqa/docformatter
    rev: eb1df347edd128b30cd3368dddc3aa65edcfac38
    hooks:
      - id: docformatter
        args: [--wrap-summaries=100, --wrap-descriptions=0, --in-place, --blank]

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
      - id: gitlint-ci

  - repo: https://github.com/python-poetry/poetry
    rev: 1.6.1
    hooks:
      - id: poetry-check
        args: ["--lock"]

  # Typo search tool
  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v7.3.1
    hooks:
      - id: cspell

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.9
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: inv mypy.run
        language: system
        pass_filenames: false
        types: [file]
        stages: [push]
      - id: run tests
        name: run tests
        entry: inv pytest.run
        language: system
        pass_filenames: false
        types: [file]
        stages: [commit]
